# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Roberto Llamosas Conde

import shutil
from pathlib import Path
import matrixai

from matrixai.parameters import load_parameter_set, validate_parameter_set
from matrixai.parser import parse_file
from matrixai.actions.parser import parse_mxact, MxactParseError
from matrixai.actions.contract import validate_action_contract


def pack_model(
    file_path: Path,
    params_path: Path | None,
    docker: bool,
    outdir: Path,
    contract_path: Path | None = None,
) -> int:
    if not file_path.exists():
        print(f"Error: El archivo de modelo '{file_path}' no existe.")
        return 1

    try:
        program = parse_file(file_path)
    except (OSError, ValueError) as exc:
        print(f"Error: El modelo MatrixAI '{file_path}' no es valido: {exc}")
        return 1

    if contract_path:
        if not contract_path.exists():
            print(f"Error: El archivo de contrato '{contract_path}' no existe.")
            return 1
        try:
            contracts = parse_mxact(contract_path.read_text(encoding="utf-8"))
        except MxactParseError as exc:
            print(f"Error: El contrato '{contract_path}' no es válido: {exc}")
            return 1
        for spec in contracts:
            result = validate_action_contract(spec, program)
            if not result.ok:
                for error in result.errors:
                    print(f"Contract validation error: {error}")
                return 1

    if params_path:
        if not params_path.exists():
            print(f"Error: El archivo de parámetros '{params_path}' no existe.")
            return 1
        try:
            parameter_set = load_parameter_set(params_path)
            parameter_validation = validate_parameter_set(program, parameter_set)
        except (OSError, ValueError) as exc:
            print(f"Error: El archivo de parámetros '{params_path}' no es valido: {exc}")
            return 1
        if not parameter_validation.ok:
            for error in parameter_validation.errors:
                print(f"Parameter error: {error}")
            return 1

    outdir.mkdir(parents=True, exist_ok=True)

    # 1. Copy model
    dest_model = outdir / file_path.name
    shutil.copy(file_path, dest_model)

    # 2. Copy parameters if provided
    params_cmd_args: list[str] = []
    if params_path:
        dest_params = outdir / params_path.name
        shutil.copy(params_path, dest_params)
        params_cmd_args = ["--params", params_path.name]

    # 3. Copy contract if provided
    contract_filename: str | None = None
    if contract_path:
        dest_contract = outdir / contract_path.name
        shutil.copy(contract_path, dest_contract)
        contract_filename = contract_path.name

    # 4. Copy MatrixAI framework source for standalone hermetic build
    matrixai_src = Path(matrixai.__file__).parent
    dest_framework = outdir / "matrixai"
    if dest_framework.exists():
        shutil.rmtree(dest_framework)
    shutil.copytree(matrixai_src, dest_framework, dirs_exist_ok=True)

    print(f"Artefactos (modelo, params y core de MatrixAI) empaquetados en '{outdir}/'.")

    if docker:
        _generate_docker_artifacts(
            outdir, file_path.name,
            params_path.name if params_path else None,
            params_cmd_args,
            contract_filename,
        )

    return 0


def _generate_docker_artifacts(
    outdir: Path,
    model_filename: str,
    params_filename: str | None,
    params_cmd_args: list[str],
    contract_filename: str | None = None,
) -> None:
    """Generate Dockerfile, docker-compose.yml, and .env.example in outdir."""

    # Build CMD list for the serve command
    contract_cmd_args = ["--contract", contract_filename] if contract_filename else []
    serve_cmd_parts = (
        [model_filename] + params_cmd_args + contract_cmd_args + ["--host", "0.0.0.0", "--port", "8000"]
    )
    cmd_json = ", ".join(f'"{p}"' for p in serve_cmd_parts)

    params_copy_line = f"COPY {params_filename} /app/" if params_filename else ""
    contract_copy_line = f"COPY {contract_filename} /app/" if contract_filename else ""

    dockerfile_content = f"""\
# MatrixAI production image — generated by `matrixai pack --docker`
# Build:  docker build -t matrixai-app .
# Deploy: copy .env.example to .env, fill in secrets, then docker compose up
FROM python:3.11-slim

WORKDIR /app
COPY matrixai/ /app/matrixai/
COPY {model_filename} /app/
{params_copy_line}
{contract_copy_line}

HEALTHCHECK --interval=30s --timeout=10s --retries=3 --start-period=10s \\
  CMD python3 -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" || exit 1

EXPOSE 8000

CMD ["python3", "-m", "matrixai", "serve", {cmd_json}]
"""

    compose_content = """\
# docker-compose.yml — MatrixAI production deployment
# Usage:
#   cp .env.example .env && $EDITOR .env   # fill in MATRIXAI_API_KEY (required)
#   docker compose up --build -d
#   curl -H "Authorization: Bearer $MATRIXAI_API_KEY" http://localhost:8000/health
services:
  matrixai-server:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python3", "-c",
             "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    volumes:
      - matrixai-registry:/data/registry

volumes:
  matrixai-registry:
"""

    env_example_content = """\
# .env.example — copy to .env and fill in your values before deploying
# Never commit .env to version control.

# ── Required ────────────────────────────────────────────────────────────────
# Bearer token for API authentication (POST /predict and POST /execute-action).
# Generate a secure value: openssl rand -hex 32
# If left empty the server auto-generates a random key at startup and prints it
# to stdout — useful for first boot, but NOT persistent across container restarts.
# Set this explicitly before production deployment.
MATRIXAI_API_KEY=

# ── Real actions (P20) ──────────────────────────────────────────────────────
# HMAC-SHA256 signing key for ActionTrace signatures (minimum 32 bytes hex).
# Required only when MATRIXAI_ALLOW_REAL_ACTIONS=true.
# Generate: openssl rand -hex 32
MATRIXAI_ACTION_SIGNING_KEY=

# Set to true to enable POST /execute-action with real side effects.
# Default: false (all actions simulated, safe for staging/CI).
MATRIXAI_ALLOW_REAL_ACTIONS=false

# ── Registry (P21) ──────────────────────────────────────────────────────────
# HMAC signing key for registry entries.
# If unset, a local key is generated per-container (not persistent across restarts).
# For production with a persistent registry volume, set this explicitly.
# Generate: openssl rand -hex 32
MATRIXAI_REGISTRY_SIGNING_KEY=

# ── Server hardening (PR4-C5) ───────────────────────────────────────────────
# Host port exposed on the Docker host (container always listens on 8000).
PORT=8000

# Maximum requests per minute per client IP (0 = disabled). Default: 60.
# MATRIXAI_RATE_LIMIT=60

# Allowed CORS origins (comma-separated). Default: * (all origins).
# Restrict for production browser clients: MATRIXAI_CORS_ORIGINS=https://app.example.com
# MATRIXAI_CORS_ORIGINS=*
"""

    (outdir / "Dockerfile").write_text(dockerfile_content, encoding="utf-8")
    (outdir / "docker-compose.yml").write_text(compose_content, encoding="utf-8")
    (outdir / ".env.example").write_text(env_example_content, encoding="utf-8")

    print("Docker artefactos generados:")
    print(f"  {outdir}/Dockerfile")
    print(f"  {outdir}/docker-compose.yml")
    print(f"  {outdir}/.env.example")
    print()
    print("Pasos para desplegar:")
    print(f"  cd {outdir}")
    print("  cp .env.example .env && $EDITOR .env   # set MATRIXAI_API_KEY")
    print("  docker compose up --build -d")
    print("  curl http://localhost:8000/health")
