"""CONTRATO 82-C4 — la plantilla del Space, que es DEL USUARIO.

*«El Space no es de MatrixAI, es de cada usuario: su modelo, sus datos,
su Space»* (Roberto, 2026-08-19). MatrixAI aporta **la plantilla**, como
ya aporta el README — y nada más: esto es TEXTO que viaja dentro del
paquete, no código que cree repositorios en la cuenta de nadie.

Publicar el Space es una casilla al publicar, nunca un efecto
automático. Crear recursos en la cuenta de alguien porque sí es
exactamente lo que este proyecto evita en todo lo demás.
"""

from __future__ import annotations

__all__ = ["SPACE_DIR", "SDK_VERSION", "space_app_py", "space_readme_md",
           "space_requirements_txt"]

#: Dónde viaja dentro del paquete.
SPACE_DIR = "space"

#: La versión de Gradio con la que se escribió esta plantilla.
#:
#: VA EN EL FRONT-MATTER Y EN LOS REQUISITOS, y no es celo: sin
#: `sdk_version`, Hugging Face elige la que quiera el día que se cree el
#: Space, así que el mismo paquete publicado con seis meses de diferencia
#: arranca sobre dos Gradio distintos — y el que falle lo hará sin que
#: nadie haya tocado nada.
SDK_VERSION = "4.44.1"


def space_requirements_txt(matrixai_version: str | None = None) -> str:
    """Lo que el SPACE necesita, que no es lo que necesita el paquete.

    Roberto, 2026-08-20: «lo he probado y no funciona». Midiéndolo salió
    esto: el `requirements.txt` del paquete lleva `numpy` y `onnxruntime`
    —lo que hace falta para PREDECIR— y el Space además **importa
    gradio** y **ejecuta `python -m matrixai verify`**. Ninguno de los dos
    viajaba.

    El botón «Is this package intact?» es el criterio de cierre del C4, y
    sin `matrixai` dentro no podía contestar nunca: un botón que siempre
    dice «no puedo comprobarlo» es peor que no tenerlo, porque se lee como
    que el paquete es el que falla.

    `matrixai_version` se FIJA cuando se conoce: el Space verifica un
    paquete que produjo una versión concreta, y verificarlo con otra
    compararía contra reglas que no son las suyas. `None` = no consta, y
    entonces se pide sin fijar en vez de inventarse un número.
    """
    # EL NOMBRE DE DISTRIBUCIÓN, no el de importación — reparado el 2026-09-16.
    # Se importa como `matrixai` (`python -m matrixai verify`, en `app.py`),
    # pero en PyPI el paquete se llama `matrixai-core` (`pyproject.toml`), y
    # `matrixai` NO EXISTE allí (404, medido). Con `matrixai==<versión>` todo
    # Space exportado fallaba al construir: pip no encontraba el paquete. Sus
    # pruebas comprobaban la CADENA, no que el paquete existiera, así que el
    # defecto pasaba en verde. Ahora la prueba lee el nombre de `pyproject.toml`.
    pin = f"matrixai-core=={matrixai_version}" if matrixai_version else "matrixai-core"
    return (
        f"gradio=={SDK_VERSION}\n"
        "numpy>=1.24\n"
        "onnxruntime>=1.16\n"
        f"{pin}\n"
    )


def space_readme_md(model_name: str) -> str:
    """El `README.md` del Space, con el front-matter que HF entiende.

    Sin front-matter, Hugging Face no reconoce el repositorio como Space
    y lo trata como ficheros sueltos: la plantilla no serviría de nada.
    """
    return f"""---
title: {model_name}
emoji: 🧮
colorFrom: blue
colorTo: indigo
sdk: gradio
sdk_version: {SDK_VERSION}
app_file: app.py
pinned: false
---

# {model_name}

A MatrixAI model you can try in the browser. Everything it needs travels
in this repository: the ONNX model, its inference spec and the recipe
that made its data.

## What this Space can and cannot do

It runs on a **free CPU Space with a time limit**. Trying the model is
fine. *Reproducing* it — rebuilding the dataset and training again — may
not fit: 300 rows and 3 epochs usually do, 20.000 rows and 50 epochs
usually do not.

When it does not fit, this Space **says so** instead of hanging or
showing half a result, and points you to the path without limits:

```bash
# download the package and check it on your own machine
matrixai verify .            # integrity + rebuild the dataset
matrixai verify . --retrain  # …and train again
```
"""


def space_app_py() -> str:
    """La app del Space.

    Usa `predict.py` y `inference_spec.json`, que YA viajan en el paquete
    desde el contrato EXPORT, en vez de reimplementar la inferencia: dos
    implementaciones de lo mismo acabarían divergiendo, y la que se vería
    en el Space no sería la que corre en casa de nadie.
    """
    return '''"""MatrixAI model — try it here.

Generated by MatrixAI as a template. It is yours: edit it freely.

This app only READS what the package carries. It does not create
repositories, upload files or ask for tokens.
"""

import json
import subprocess
import sys
from pathlib import Path

import gradio as gr

AQUI = Path(__file__).resolve().parent


def _junto_a_mi(nombre):
    """Busca en ESTA carpeta y en la de arriba.

    Dentro del paquete esta plantilla vive en `space/` y los artefactos
    están un nivel por encima. Publicado como Space, Hugging Face exige
    `app.py` en la RAÍZ y los artefactos acaban a su lado. Buscar en los
    dos sitios hace que el mismo fichero valga para los dos casos, en vez
    de tener dos versiones que acabarían divergiendo.
    """
    for base in (AQUI, AQUI.parent):
        candidato = base / nombre
        if candidato.is_file():
            return candidato
    return AQUI / nombre


# Lo que el paquete YA trae. Si falta, se dice: una app que finge predecir
# sobre un paquete incompleto es peor que una que explica qué falta.
SPEC = _junto_a_mi("inference_spec.json")
PREDICT = _junto_a_mi("predict.py")
PAQUETE = PREDICT.parent

# Un Space gratuito es CPU con tope de tiempo: probar el modelo cabe,
# reproducirlo entero puede no caber. Se dice ARRIBA, no cuando ya se ha
# agotado el tiempo.
LIMITES = (
    "This Space runs on free CPU with a time limit. Trying the model fits; "
    "rebuilding its dataset and training again may not. For that, download "
    "the package and run `matrixai verify . --retrain` on your own machine."
)


def _campos():
    if not SPEC.is_file():
        return []
    try:
        spec = json.loads(SPEC.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    entradas = spec.get("inputs") or spec.get("input_fields") or []
    return [str(c.get("name") or c) for c in entradas if c]


def verificar():
    """El resultado de `matrixai verify`, DENTRO del Space.

    AUDITORÍA EXTERNA (2026-08-20) [BLOQUEANTE de cierre del C4]: la
    plantilla solo ejecutaba `predict.py`. El criterio de cierre del C4
    pide que el Space **enseñe el resultado del C2**, y sin eso el Space
    invita a probar un modelo sin decir si el paquete está íntegro — que
    es justo lo contrario de para lo que existe una ficha ejecutable.

    Se ejecuta el `verify` del paquete y se enseña **su informe tal cual**:
    aquí no se interpreta nada. Si matrixai no está instalado en el Space,
    se dice — un botón que falla en silencio se lee como que no hay nada
    que comprobar.
    """
    try:
        salida = subprocess.run(
            [sys.executable, "-m", "matrixai", "verify", str(PAQUETE)],
            capture_output=True, text=True, timeout=120, cwd=str(PAQUETE))
    except FileNotFoundError:
        return ("matrixai is not installed in this Space, so integrity cannot "
                "be checked here. Run `matrixai verify .` after downloading.")
    except subprocess.TimeoutExpired:
        return "Verification took too long for a free CPU Space. " + LIMITES
    informe = (salida.stdout or "").strip() or (salida.stderr or "").strip()
    # Los tres códigos NO se colapsan, igual que en el CLI: 0 cuadra,
    # 2 alguien lo tocó, 3 no se pudo comprobar.
    veredicto = {0: "PASS — nothing failed",
                 2: "FAIL — something does not match what the package declares",
                 3: "NOT FULLY CHECKED — some stage could not be compared"}.get(
                     salida.returncode, f"exit code {salida.returncode}")
    return f"{veredicto}\\n\\n{informe}"


def predecir(*valores):
    if not PREDICT.is_file():
        return "This package does not carry predict.py, so it cannot run here."
    campos = _campos()
    entrada = {n: v for n, v in zip(campos, valores)}
    try:
        salida = subprocess.run(
            [sys.executable, str(PREDICT), "--json", json.dumps(entrada)],
            capture_output=True, text=True, timeout=60, cwd=str(PAQUETE))
    except subprocess.TimeoutExpired:
        return "It took too long for a free CPU Space. " + LIMITES
    if salida.returncode != 0:
        return f"predict.py failed:\\n{salida.stderr[:2000]}"
    return salida.stdout.strip() or "(no output)"


CAMPOS = _campos()
with gr.Blocks() as demo:
    gr.Markdown("# Try this model")
    gr.Markdown(LIMITES)

    # LA INTEGRIDAD, ARRIBA Y ANTES DE PROBAR NADA. Un Space que invita a
    # predecir sin decir si el paquete cuadra convierte una ficha
    # ejecutable en una demo.
    gr.Markdown("## Is this package intact?")
    salida_verify = gr.Textbox(label="matrixai verify", lines=12)
    gr.Button("Verify this package").click(verificar, inputs=None,
                                           outputs=salida_verify)

    gr.Markdown("## Try it")
    if CAMPOS:
        entradas = [gr.Textbox(label=n) for n in CAMPOS]
        salida = gr.Textbox(label="Prediction")
        gr.Button("Predict").click(predecir, inputs=entradas, outputs=salida)
    else:
        gr.Markdown(
            "This package does not declare its input fields "
            "(`inference_spec.json` is missing or unreadable), so the form "
            "cannot be built. The model file is still here to download."
        )

if __name__ == "__main__":
    demo.launch()
'''
